C={}
def put(cat,names,what=''):
  for n in names.split('|'):C[n]=(cat,what)
put('fashion','New Yorker|RE|Calzedonia|Zarina|Tom Tailor|Van Cliff|Bulmer|Kanzler|Top People|Levi\'s|Elny|Henderson|Zolla|Love Republic|Camel Active|Terranova|befree|Desired|Gloria Jeans|Zimaletto|Clever|Michelle|Мята|Алеф|Magnus|Barkland|Дибони|Снежная Королева|Rocky Boxer|5КармаNов|Mrk|Malmaran|Climber|Viva|Сударь','Одежда и обувь')
put('fashion','SneakerBox','Кроссовки')
put('kids','Re Kids','Детская одежда')
put('kids','Мисти Парк','Детский развлекательный парк')
put('kids','Кигурумер','Кигуруми и пижамы')
put('kids','Happy Cars|Паровозик','Детские аттракционы')
put('beauty','Лэтуаль|Рив Гош|Et.b Parfum|Perfums Bar|Parfum Oil|Marav Parfum|Zielinski & Rozen','Косметика и парфюмерия')
put('beauty','Yves Rocher|Natura Siberica|MayaKorea','Косметика')
put('beauty','Ригла','Аптека')
put('acc','Наше серебро|MIUZ Diamonds|585 Золотой|Adamas|Sokolov|Gamma D\'oro|Cleopatra|Unode50|Гламурный акцент','Ювелирные украшения')
put('acc','Мир часов|AllTime Casio','Часы')
put('acc','Бриллиантовая ручка','Подарочные ручки и аксессуары')
put('acc','Счастливый взгляд|ABC оптика|Очки Плюс|Айкрафт','Оптика')
put('tech','The iStore|re:premium','Техника Apple')
put('tech','МегаФон | Yota|T2|билайн|Хорошая связь','Салон связи')
put('tech','Save Phone|Броноскинс|Print Cases|Чехломат|Volt Mix|Бери заряд|Energo','Аксессуары для телефонов')
put('tech','Haier','Бытовая техника')
put('food','Кофе культ|John Coffey|Heart of Coffee|Barista|Большой стакан|Vendpresso','Кофейня')
put('food','Престо','Ресторан')
put('food','Хлебный дом','Пекарня')
put('food','Суши-Маркет','Суши')
put('food','Терри','Кафе')
put('food','Перекрёсток Select','Магазин у дома')
put('gifts','Мармеладный рай|Gold Gum|Снеки','Сладости')
put('gifts','Мир Подарков','Подарки')
put('furn','Мебель Шара|Soft Place|Moon|Мебельград|Правила мебели|Галерея мебели|Артис|Лером|Сонум|Диван Босс|Много Мебели','Мебель')
put('furn','Askona|Ormatek','Матрасы и сон')
put('home','Дом Лента','Гипермаркет товаров для дома')
put('home','Садовый рай','Товары для сада')
put('home','Kuchenland Home','Посуда и кухня')
put('home','Копицентр Офисмаг|Офисмаг','Канцтовары и офис')
put('home','Четыре Лапы|Мой Котя','Зоотовары')
put('home','Авточехлы','Автотовары')
put('sport','Спортмастер Pro','Спортивные товары')
put('sport','2scoop|El Vitamino','Спортивное питание')
put('serv','СберБанк','Банк')
put('serv','Key 71','Изготовление ключей')
put('serv','Pro Сервис','Ремонт техники')
put('serv','Диана','Ателье')
put('serv','Кеша хороший!','Груминг')
put('serv','Пункт приёма вторсырья','Приём вторсырья')
put('serv','Korf X','Доставка и почта')
put('serv','Белое облако','Магазин')
put('kids','Аладдин|Justmint','Развлечения')
C['Rocky Boxer']=('kids','Развлечения')
put('food','Микрозелень','Микрозелень и салаты')
